### ISSUE TITLE
Unable to see my Ark Ascended game server? 

### ISSUE THREAD

**Issue by NRmash** [azixus/ARK_Ascended_Docker#27] opened 2023-12-13 12:00 UTC
Hi,

unfortunately you cannot see or find my ARK_Ascended_Docker server in ASA.
if you connect it with "open ip:port" then it works.
Does anyone have an idea?

Greetings from Germany

**Comment by nicti** [comment] 2023-12-13 14:15
The problem is caused by the client and not the server. Running ```Ark.UseServerList 0``` in the game terminal does resolve the problem for the running instance of the game.

**Comment by NRmash** [comment] 2023-12-13 16:17
> The problem is caused by the client and not the server. Running `Ark.UseServerList 0` in the game terminal does resolve the problem for the running instance of the game.

Ahh thx :D
Do you happen to know if this can be included in the ASA client start parameters?

**Comment by azixus** [comment] 2023-12-14 15:27
> > The problem is caused by the client and not the server. Running `Ark.UseServerList 0` in the game terminal does resolve the problem for the running instance of the game.
> 
> Ahh thx :D Do you happen to know if this can be included in the ASA client start parameters?

I wasn't able to find a way to run it automatically. I'll close the issue for now, but I'll have a look at the ASA networking in a bit to see if I can find a server side fix.

**Closed as not planned by azixus** 2023-12-14 15:27 UTC

**Comment by azixus** [comment] 2023-12-14 18:14
Quite odd, they replaced the calls to the EOS matchmaking APIs by a query to 
https://cdn2.arkdedicated.com/servers/asa/unofficialserverlist.json to download a 44MiB server list on every refresh. Seems like a weird decision, nothing I can do atm.
